name: example
description: A new Flutter project.

vars:
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  neubrutalism_ui:
    path: ..
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.4
  get_it: ^8.0.3
  shared_preferences: ^2.5.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  go_router: ^14.7.2
  camerawesome: ^2.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
